version: '3.9'
services:
  db:
    container_name: db
    restart: always
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    image: postgres:15-alpine
    volumes:
      - db_dev:/var/lib/postgresql/data
    env_file:
      - .env
    command: -p ${POSTGRES_PORT}

  backend:
    container_name: backend
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    build:
      context: ../backend
      dockerfile: Dockerfile
    env_file:
      - .env
    restart: always
    command: "sh ./entrypoint.sh"
    logging:
      driver: journald
    volumes:
      - ./entrypoint.sh:/backend/entrypoint.sh
      - ../backend:/backend
    depends_on:
      - db

  auth-bot:
    container_name: auth-bot
    restart: always
    build:
      context: ../auth_bot
      dockerfile: Dockerfile
    logging:
      driver: journald
    command: "sh ./start_bot.sh"
    env_file:
      - .env
    volumes:
      - ./start_bot.sh:/bot/start_bot.sh
      - ../auth_bot:/bot
    depends_on:
      - backend



volumes:
  db_dev:
